### ISSUE TITLE
vsis3 + vsizip is broken

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/intake-dcat#10]
GDAL uses path prefixes to decide how to open compressed or remote files. This includes `vsicurl` (for http resources) ,`vsis3` (for resources on s3), and `vsizip` for zipped resources. Currently, we can handle each of these, but combining them as when a zipped file is loaded to s3 is broken. This will often be the case for uploaded shapefiles.

I'm unsure whether the best fix for this should be here, or in `intake_geopandas`.

**Comment by martindurant** [comment]
I don't suppose it can take a python file-like object?

**Comment by ian-r-rose** [comment]
Unfortunately, I don't think it can take a file-like object. I presume you are interested in that for `ffspec` reasons?

GDAL/OGR uses its own file-system abstraction layer for things like archives and URLs: https://gdal.org/user/virtual_file_systems.html This is all pretty low-level compiled C code, and `fiona` mostly delegates to that by assembling the correct paths for that system.

I think what is required in this case to to assemble a compound protocol (e.g. `zip+s3://`), as per [this](https://fiona.readthedocs.io/en/latest/manual.html#cloud-storage-credentials) documentation.

**Comment by martindurant** [comment]
Yes, I am forever pushing fsspec; but I suspected that C-land stuff like GDAL would be against it. Then again, since hdf5 now *does*, there is hope for that kind of thing.

The other solution would be to use FUSE, but it comes with many caveats, not least poor performance. fsspec can FUSE, and so can several other implementations for various specific providers like s3.
